version: 2
jobs:
    build:
        working_directory: ~/repo
        docker:
            - image: circleci/php:7.1-browsers
        steps:
            - checkout
            - restore_cache:
                keys:
                - vendor-{{ checksum "composer.lock" }}
            - run: composer install -n --prefer-dist
            - save_cache:
                key: vendor-{{ checksum "composer.lock" }}
                paths:
                    - vendor
    test:
        docker:
            - image: circleci/php:7.1-browsers
        steps:
            - checkout
            - restore_cache:
                keys:
                - vendor-{{ checksum "composer.lock" }}
            - run: composer install -n --prefer-dist
            - save_cache:
                key: vendor-{{ checksum "composer.lock" }}
                paths:
                    - vendor
            - run:
                name: Run tests
                command: ./bin/phpunit --log-junit junit.xml
            - store_artifacts:
                path: junit.xml
                prefix: tests
workflows:
    version: 2
    build_and_test:
        jobs:
            - build
            - test:
                requires:
                    - build
                filters:
                    branches:
                        only: master
